from fpdf import FPDF
import os

os.makedirs("mock_policies", exist_ok=True)

# 1. Leave Policy
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=15)
pdf.cell(200, 10, txt="Company Leave Policy v2", ln=1, align="C")
pdf.set_font("Arial", size=12)
pdf.ln(10)
content = """Section 3.2 - Sick Leaves
All full-time employees are entitled to 12 sick leaves per year.
These are credited on January 1st and cannot be carried forward to the next year.
If you need to take a sick leave, please inform your manager as early as possible.
Medical certificates are required for sick leaves exceeding 3 consecutive days.

Section 3.3 - Casual Leaves
Employees are entitled to 6 casual leaves per year. These must be approved 48 hours in advance.
"""
pdf.multi_cell(0, 10, txt=content)
pdf.output("mock_policies/Company_Leave_Policy_v2.pdf")

# 2. Payroll Guidelines
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=15)
pdf.cell(200, 10, txt="Payroll Guidelines 2024", ln=1, align="C")
pdf.set_font("Arial", size=12)
pdf.ln(10)
content = """Section 4.1 - Payslips and Salary Credit
Your monthly salary will be credited to your registered bank account by the last working day of the month.
The monthly payslip is generated by the 2nd of the following month. 
You can access your payslip via the Promtal HR Portal under the 'My Documents' section.

Section 4.2 - Deductions
Standard deductions including Provident Fund (PF) and Professional Tax (PT) will be applied as per government regulations.
"""
pdf.multi_cell(0, 10, txt=content)
pdf.output("mock_policies/Payroll_Guidelines_2024.pdf")

print("Mock PDFs generated successfully in 'mock_policies' directory.")
